spring:
    application:
        name: auth
    datasource:
        url: jdbc:postgresql://postgres:5432/authdb
        username: authdb-user
        password: secret
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
    # security:
    #     user:
    #         name: user
    #         password: password
    #     oauth2:
    #         authorizationserver:
    #             client:
    #                 oidc-client:
    #                     registration:
    #                         client-id: "amason-user-manager"
    #                         client-secret: "gexLQ8q3FVKA6GJwdBt2MrmWsv479YnH"
    #                         client-authentication-methods:
    #                             - "client_secret_basic"
    #                         authorization-grant-types:
    #                             - "authorization_code"
    #                             - "refresh_token"
    #                         redirect-uris:
    #                             - "http://127.0.0.1:4000/api/auth/callback/amason-provider"
    #                         post-logout-redirect-uris:
    #                             - "http://127.0.0.1:4000/"
    #                         scopes:
    #                             - "openid"
    #                             - "profile"
    #                     require-authorization-consent: true